Fix shortened Session Id display
aerokube/selenoid-ui pull request #511
Opened 2022-12-07 14:17 UTC by bereg2k

## Changes

Fixed the displaying of the short version of the Session ID on the Session's container:

### Before
<img width="734" alt="image" src="https://user-images.githubusercontent.com/42677987/206201328-fea00664-ca9c-4011-bfc0-cdd76ca3b69c.png">

### After
<img width="791" alt="image" src="https://user-images.githubusercontent.com/42677987/206202090-06d50f0e-1e52-4375-aa38-57aa8729d27a.png">

2022-12-08 09:56 UTC, bereg2k commented on ui/src/components/Sessions/index.js
> +                    {id.substring(0, 8)}
Sounds reasonable.
Could please give me a use case where this `id.indexOf("-")` was useful?

2022-12-08 11:46 UTC, lanwen commented on ui/src/components/Sessions/index.js
> +                    {id.substring(0, 8)}
in the early versions we used uuid as session ids

2022-12-08 12:56 UTC, bereg2k commented on ui/src/components/Sessions/index.js
> +                    {id.substring(0, 8)}
Got it. 
Fixed according to your comment.

2022-12-08 12:57 UTC, lanwen approved these changes

2022-12-08 15:42 UTC, lanwen commented
I think the closing ) is missing now

2022-12-08 15:42 UTC, lanwen requested changes

2022-12-08 15:42 UTC, lanwen commented on ui/src/components/Sessions/index.js
> +                    {id.substring(0, id.indexOf('-') === -1 ? 8 : id.indexOf('-')}
```suggestion
                    {id.substring(0, id.indexOf('-') === -1 ? 8 : id.indexOf('-'))}
```

2022-12-08 16:14 UTC, merged

2022-12-08 19:46 UTC, bereg2k commented
> I think the closing ) is missing now

Yep, thanks for the correction, I was too busy copypasting :)

2023-01-16 11:04 UTC, lanwen commented
@bereg2k thanks for the ping, triggered https://github.com/aerokube/selenoid-ui/releases/tag/1.10.9

2023-01-16 14:15 UTC, bereg2k commented
@lanwen thanks!